version: '2'
services:
    simpleyahtzeeapp-app:
        image: simpleyahtzeeapp
        external_links:
            - simpleyahtzeeapp-postgresql:postgresql
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://postgresql:5432/SimpleYahtzeeApp
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    simpleyahtzeeapp-postgresql:
        extends:
            file: postgresql.yml
            service: simpleyahtzeeapp-postgresql
